spring:
  servlet:
    multipart:
        maxFileSize: 3MB # 파일 하나의 최대 크기
        maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량
  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:account;MODE=MySQL;
    username: SA
    password:


cloud:
  aws:
    credentials:
      accessKey:  ${AWS_ACCESS_KEY_ID}
      secretKey:  ${AWS_SECRET_ACCESS_KEY}
    s3:
      nameSpace: ${BUCKET_NAMESPACE}
      bucket: ${BUCKET_NAME}
      dir: /image
    region:
      static: ap-chuncheon-1
    stack:
      auto: false